version: '2.1'

services:
  localstack:
    container_name: "localstack-local"
    image: localstack/localstack
    ports:
      - "4563-4599:4563-4599"
      - "8080:8080"
    environment:
      - SERVICES=lambda,sqs,sns,s3,cloudwatch,dynamodb,apigateway
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - AWS_DEFAULT_OUTPUT=json
      - AWS_REGION='us-west-2'
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - START_WEB=1
    volumes:
      - "./localstack_data:/tmp/localstack"
      - "./app-to-upload:/app-to-upload"
      - ./startup-scripts:/docker-entrypoint-initaws.d
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./api-serverless:/api-serverless"
    privileged: true