version: '2.1'

services:
  localstack:
    container_name: "localstack-local"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=lambda,sqs,sns,s3,apigateway,cloudwatch,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
      # - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      # - DOCKER_HOST=unix:///var/run/docker.sock
      # - HOST_TMP_FOLDER=${TMPDIR}
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack_data:/tmp/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"